Update script

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,4 +1,7 @@
-# triggered by schedule 
+# triggered by schedule
+trigger: none
+pr: none
+
 schedules:
 - cron: '0 0 * * *'
   displayName: Daily midnight build
@@ -7,49 +10,53 @@ schedules:
     - main
   always: true
 
-pr: none
-
 pool:
   vmImage: 'ubuntu-latest'
 
-steps:
-- task: DownloadSecureFile@1
-  inputs:
-    secureFile: vscode_typescript_next_deploy_key
-  displayName: 'Get the deploy key'
+resources:
+  repositories:
+    - repository: templates
+      type: github
+      name: microsoft/vscode-typescript-next
+      ref: main
+      endpoint: Monaco
 
-- bash: |
-    chmod +x ./build/updateGrammar.sh
-    ./build/updateGrammar.sh 
-    grammarResult=$?
-    if [ $grammarResult -neq 0 ] ; then
-        echo "Unexpected error while updating grammar"
-        exit $grammarResult
-    fi
+extends:
+  template: azure-pipelines/extension/pre-release.yml@templates
+  parameters:
+    usePreReleaseChannel: false
+    buildSteps:
+      - bash: |
+        chmod +x ./build/updateGrammar.sh
+        ./build/updateGrammar.sh 
+        grammarResult=$?
+        if [ $grammarResult -neq 0 ] ; then
+            echo "Unexpected error while updating grammar"
+            exit $grammarResult
+        fi
 
-    chmod +x ./build/bumpAndPublish.sh
-    ./build/bumpAndPublish.sh '$(marketplace_key)'
-    result=$?
+        npm run bump-version
+        result=$?
 
-    set -e
-    if [ $result -eq 0 ]; then
-      git config --local user.name "Azure Pipelines"
-      git config --local user.email "azuredevops@microsoft.com"
-      git add .
-      git commit -m "Publishing version bump ***NO_CI***"
+        set -e
+        if [ $result -eq 0 ]; then
+          git config --local user.name "Azure Pipelines"
+          git config --local user.email "azuredevops@microsoft.com"
+          git add .
+          git commit -m "Publishing version bump ***NO_CI***"
 
-      mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
-      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
-      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
-      git remote set-url --push origin git@github.com:microsoft/vscode-typescript-next.git
-      git push origin HEAD:main
+          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
+          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+          git remote set-url --push origin git@github.com:microsoft/vscode-typescript-next.git
+          git push origin HEAD:main
 
-      exit
-    elif [ $result -eq 1 ]; then
-        echo "Skipping publish"
-        exit
-    else
-        echo "Unexpected error"
-        exit $result
-    fi
-  displayName: 'Publish to marketplace'
+          exit
+        elif [ $result -eq 1 ]; then
+            echo "Skipping publish"
+            exit
+        else
+            echo "Unexpected error"
+            exit $result
+        fi
+      displayName: 'Publish to marketplace'
