Update script indent

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -27,36 +27,36 @@ extends:
     usePreReleaseChannel: false
     buildSteps:
       - bash: |
-        chmod +x ./build/updateGrammar.sh
-        ./build/updateGrammar.sh 
-        grammarResult=$?
-        if [ $grammarResult -neq 0 ] ; then
-            echo "Unexpected error while updating grammar"
-            exit $grammarResult
-        fi
+          chmod +x ./build/updateGrammar.sh
+          ./build/updateGrammar.sh
+          grammarResult=$?
+          if [ $grammarResult -neq 0 ] ; then
+              echo "Unexpected error while updating grammar"
+              exit $grammarResult
+          fi
 
-        npm run bump-version
-        result=$?
+          npm run bump-version
+          result=$?
 
-        set -e
-        if [ $result -eq 0 ]; then
-          git config --local user.name "Azure Pipelines"
-          git config --local user.email "azuredevops@microsoft.com"
-          git add .
-          git commit -m "Publishing version bump ***NO_CI***"
+          set -e
+          if [ $result -eq 0 ]; then
+            git config --local user.name "Azure Pipelines"
+            git config --local user.email "azuredevops@microsoft.com"
+            git add .
+            git commit -m "Publishing version bump ***NO_CI***"
 
-          mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
-          chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
-          git remote set-url --push origin git@github.com:microsoft/vscode-typescript-next.git
-          git push origin HEAD:main
+            mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
+            chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
+            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+            git remote set-url --push origin git@github.com:microsoft/vscode-typescript-next.git
+            git push origin HEAD:main
 
-          exit
-        elif [ $result -eq 1 ]; then
-            echo "Skipping publish"
             exit
-        else
-            echo "Unexpected error"
-            exit $result
-        fi
+          elif [ $result -eq 1 ]; then
+              echo "Skipping publish"
+              exit
+          else
+              echo "Unexpected error"
+              exit $result
+          fi
       displayName: 'Publish to marketplace'
